version: "3.7"
services:
#  gateway:
#    build:
#      context: gateway/docker
#      dockerfile: development/nginx/Dockerfile
#     ports:
#       - "8080:8080"
#      - "8081:8081"
#      - "8082:8082"
#    depends_on:
#      - frontend

  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"

  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app

volumes:
  api-postgres: